using UnityEngine;
using UnityEngine.UI;

public sealed class RestoreHUD : MonoBehaviour
{
    private RestorationManager manager;
    private Text progressText, instructionText, toolNameText;
    private Image progressFill;
    private readonly Image[] toolCards=new Image[5];
    private readonly Image[] toolIcons=new Image[5];
    private readonly Text[] toolLabels=new Text[5];
    private readonly Text[] toolStates=new Text[5];
    private GameObject completion;
    private bool built;
    private float displayedProgress;
    private static Sprite roundedSprite;
    private static readonly Color Ink=new Color32(31,45,51,255);
    private static readonly Color Muted=new Color32(104,121,126,255);
    private static readonly Color Accent=new Color32(45,158,177,255);
    private static readonly Color PanelWhite=new Color(1,1,1,.94f);
    private static readonly string[] Names={"WATER","FOAM","BRUSH","RINSE","DRY"};

    [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)] private static void Boot(){GameObject go=new GameObject("Restore HUD");go.AddComponent<RestoreHUD>();}
    private void Start()=>TryInitialise();
    private void TryInitialise(){if(built)return;if(manager==null)manager=FindFirstObjectByType<RestorationManager>();if(manager==null)return;HideLegacyUI();Build();built=true;}
    private void HideLegacyUI(){GameObject old=GameObject.Find("UI Manager");if(old==null)return;Canvas c=old.GetComponentInChildren<Canvas>();if(c!=null)c.gameObject.SetActive(false);}

    private void Build(){GameObject c=new GameObject("Restore HUD Canvas");c.transform.SetParent(transform,false);Canvas canvas=c.AddComponent<Canvas>();canvas.renderMode=RenderMode.ScreenSpaceOverlay;canvas.sortingOrder=50;CanvasScaler s=c.AddComponent<CanvasScaler>();s.uiScaleMode=CanvasScaler.ScaleMode.ScaleWithScreenSize;s.referenceResolution=new Vector2(1080,1920);s.matchWidthOrHeight=.5f;c.AddComponent<GraphicRaycaster>();BuildHeader(c.transform);BuildInstruction(c.transform);BuildToolDock(c.transform);BuildCompletion(c.transform);}

    private void BuildHeader(Transform p){Image panel=RoundedPanel(p,new Vector2(.5f,.925f),new Vector2(900,112),PanelWhite);Text title=Text(panel.transform,"RESTORE",new Vector2(.18f,.64f),new Vector2(250,32),20,FontStyle.Bold,Ink);title.alignment=TextAnchor.MiddleLeft;progressText=Text(panel.transform,"0%",new Vector2(.82f,.64f),new Vector2(130,32),20,FontStyle.Bold,Accent);progressText.alignment=TextAnchor.MiddleRight;Text(panel.transform,"ASMR  •  TAKE YOUR TIME",new Vector2(.5f,.34f),new Vector2(360,20),9,FontStyle.Bold,Muted);Image track=RoundedPanel(panel.transform,new Vector2(.5f,.08f),new Vector2(800,8),new Color32(224,232,233,255));progressFill=RoundedPanel(track.transform,new Vector2(.5f,.5f),new Vector2(800,8),Accent);progressFill.rectTransform.anchorMin=Vector2.zero;progressFill.rectTransform.anchorMax=Vector2.one;progressFill.rectTransform.offsetMin=progressFill.rectTransform.offsetMax=Vector2.zero;progressFill.type=Image.Type.Filled;progressFill.fillMethod=Image.FillMethod.Horizontal;progressFill.fillOrigin=0;progressFill.fillAmount=0;}

    private void BuildInstruction(Transform p){Image panel=RoundedPanel(p,new Vector2(.5f,.785f),new Vector2(840,70),new Color(1,1,1,.78f));Text(panel.transform,"NOW",new Vector2(.11f,.5f),new Vector2(75,24),8,FontStyle.Bold,Muted);toolNameText=Text(panel.transform,"WATER",new Vector2(.27f,.5f),new Vector2(175,28),14,FontStyle.Bold,Ink);instructionText=Text(panel.transform,"Drag gently across the muddy areas",new Vector2(.67f,.5f),new Vector2(500,42),13,FontStyle.Normal,Ink);}

    private void BuildToolDock(Transform p){Image dock=RoundedPanel(p,new Vector2(.5f,.105f),new Vector2(960,172),new Color32(24,39,44,245));Text(dock.transform,"TOOLS",new Vector2(.5f,.83f),new Vector2(220,18),8,FontStyle.Bold,new Color(1,1,1,.42f));for(int i=0;i<5;i++){int n=i;Image card=RoundedPanel(dock.transform,new Vector2(.5f,.39f),new Vector2(156,100),new Color(1,1,1,.065f));card.rectTransform.anchoredPosition=new Vector2(-384+i*192,-4);toolCards[i]=card;Image icon=RoundedPanel(card.transform,new Vector2(.5f,.69f),new Vector2(44,44),new Color(1,1,1,.10f));icon.sprite=CreateIconSprite(i);icon.preserveAspect=true;toolIcons[i]=icon;toolLabels[i]=Text(card.transform,Names[i],new Vector2(.5f,.25f),new Vector2(145,20),8,FontStyle.Bold,Color.white);toolStates[i]=Text(card.transform,"LOCKED",new Vector2(.5f,.08f),new Vector2(145,16),6,FontStyle.Bold,new Color(1,1,1,.30f));Button b=card.gameObject.AddComponent<Button>();b.targetGraphic=card;ColorBlock cb=b.colors;cb.normalColor=Color.white;cb.highlightedColor=new Color(1,1,1,.95f);cb.pressedColor=new Color(.88f,.96f,.97f,1);cb.disabledColor=new Color(1,1,1,.45f);b.colors=cb;b.onClick.AddListener(()=>manager.SetTool((CleaningTool)n));}}

    private void BuildCompletion(Transform p){completion=new GameObject("Completion");completion.transform.SetParent(p,false);RectTransform root=completion.AddComponent<RectTransform>();root.anchorMin=Vector2.zero;root.anchorMax=Vector2.one;root.offsetMin=root.offsetMax=Vector2.zero;Image dim=completion.AddComponent<Image>();dim.color=new Color(.02f,.07f,.08f,.58f);Image card=RoundedPanel(completion.transform,new Vector2(.5f,.5f),new Vector2(820,470),PanelWhite);Text(card.transform,"RESTORED",new Vector2(.5f,.67f),new Vector2(650,58),34,FontStyle.Bold,Ink);Text(card.transform,"A little care makes a big difference.",new Vector2(.5f,.47f),new Vector2(700,48),17,FontStyle.Normal,Muted);Text(card.transform,"✦   ✦   ✦",new Vector2(.5f,.28f),new Vector2(500,50),23,FontStyle.Bold,Accent);completion.SetActive(false);}

    private void Update(){TryInitialise();if(!built)return;float target=Mathf.Clamp01(manager.Progress);displayedProgress=Mathf.MoveTowards(displayedProgress,target,Time.deltaTime*.9f);progressText.text=Mathf.RoundToInt(displayedProgress*100f)+"%";progressFill.fillAmount=displayedProgress;toolNameText.text=manager.CurrentTool.Label();instructionText.text=GetInstruction(manager.CurrentTool);int stage=Mathf.Clamp(manager.StageIndex,0,4);for(int i=0;i<5;i++){bool active=i==stage,unlocked=i<=manager.StageIndex;toolCards[i].color=active?Accent:unlocked?new Color(1,1,1,.13f):new Color(1,1,1,.055f);toolIcons[i].color=active?Color.white:unlocked?new Color(1,1,1,.72f):new Color(1,1,1,.25f);toolLabels[i].color=active?Color.white:unlocked?new Color(1,1,1,.72f):new Color(1,1,1,.25f);toolStates[i].text=active?"ACTIVE":unlocked?"READY":"LOCKED";toolStates[i].color=active?new Color(1,1,1,.80f):new Color(1,1,1,.30f);toolCards[i].GetComponent<Button>().interactable=unlocked&&!manager.IsComplete;}if(manager.IsComplete&&!completion.activeSelf)completion.SetActive(true);}
    private static string GetInstruction(CleaningTool t){switch(t){case CleaningTool.Water:return "Let the water loosen the dirt";case CleaningTool.Foam:return "Spread the soft foam slowly";case CleaningTool.Brush:return "Slowly scrub and listen";case CleaningTool.Rinse:return "Rinse away the loosened dirt";case CleaningTool.Dryer:return "Gently dry the clean surface";default:return "Restore it at your own pace";}}

    private static Image RoundedPanel(Transform parent,Vector2 anchor,Vector2 size,Color color){GameObject go=new GameObject("Panel");go.transform.SetParent(parent,false);RectTransform r=go.AddComponent<RectTransform>();r.anchorMin=r.anchorMax=anchor;r.anchoredPosition=Vector2.zero;r.sizeDelta=size;Image image=go.AddComponent<Image>();image.sprite=GetRoundedSprite();image.type=Image.Type.Sliced;image.color=color;return image;}
    private static Sprite GetRoundedSprite(){if(roundedSprite!=null)return roundedSprite;const int size=64;const float radius=14f;Texture2D t=new Texture2D(size,size,TextureFormat.RGBA32,false);t.filterMode=FilterMode.Bilinear;Color[] px=new Color[size*size];for(int y=0;y<size;y++)for(int x=0;x<size;x++){float dx=Mathf.Max(radius-x,x-(size-1-radius),0f),dy=Mathf.Max(radius-y,y-(size-1-radius),0f);float d=Mathf.Sqrt(dx*dx+dy*dy);px[y*size+x]=new Color(1,1,1,d<=radius?1f:0f);}t.SetPixels(px);t.Apply(false,true);roundedSprite=Sprite.Create(t,new Rect(0,0,size,size),new Vector2(.5f,.5f),64f,0,SpriteMeshType.FullRect,new Vector4(18,18,18,18));return roundedSprite;}

    private static Sprite CreateIconSprite(int tool){const int size=64;Texture2D t=new Texture2D(size,size,TextureFormat.RGBA32,false);t.filterMode=FilterMode.Bilinear;Color[] px=new Color[size*size];for(int i=0;i<px.Length;i++)px[i]=new Color(1,1,1,0);for(int y=0;y<size;y++)for(int x=0;x<size;x++){float X=x-31.5f,Y=y-31.5f,R=Mathf.Sqrt(X*X+Y*Y);bool on=false;switch(tool){case 0:float dx=X*.9f,dy=Y+7f;on=(dx*dx+dy*dy<225f&&Y<13f)||(Mathf.Abs(X)<3f&&Y>8f&&Y<27f);break;case 1:on=Mathf.Abs(R-13f)<3f||Mathf.Abs(Mathf.Sqrt((X+13)*(X+13)+(Y-8)*(Y-8))-8f)<3f||Mathf.Abs(Mathf.Sqrt((X-12)*(X-12)+(Y+9)*(Y+9))-6f)<3f;break;case 2:on=(Mathf.Abs(X+Y*.7f)<5f&&Y>-17f&&Y<17f)||(Mathf.Abs(Y-19f)<5f&&Mathf.Abs(X)<22f);break;case 3:on=(Mathf.Abs(X+17f)<4f&&Mathf.Abs(Y)<20f)||(X>-6f&&X<21f&&Mathf.Abs(Y-X*.55f)<3f)||(X>-6f&&X<21f&&Mathf.Abs(Y+X*.55f)<3f);break;default:on=(Mathf.Abs(X+14f)<4f&&Mathf.Abs(Y)<17f)||(Mathf.Abs(Y)<4f&&X>-10f&&X<21f)||(Mathf.Abs(Y-10f)<3f&&X>-4f&&X<20f)||(Mathf.Abs(Y+10f)<3f&&X>-4f&&X<20f);break;}if(on)px[y*size+x]=Color.white;}t.SetPixels(px);t.Apply(false,true);return Sprite.Create(t,new Rect(0,0,size,size),new Vector2(.5f,.5f),64f);}

    private static Text Text(Transform parent,string value,Vector2 anchor,Vector2 size,int fontSize,FontStyle style,Color color){GameObject go=new GameObject("Label");go.transform.SetParent(parent,false);RectTransform r=go.AddComponent<RectTransform>();r.anchorMin=r.anchorMax=anchor;r.anchoredPosition=Vector2.zero;r.sizeDelta=size;Text t=go.AddComponent<Text>();t.text=value;t.font=Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");t.fontSize=fontSize;t.fontStyle=style;t.alignment=TextAnchor.MiddleCenter;t.color=color;t.horizontalOverflow=HorizontalWrapMode.Wrap;t.verticalOverflow=VerticalWrapMode.Overflow;return t;}
}
